---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devstudio-settings
  namespace: {{ $.Release.Namespace }}
  labels:
    app: devstudio
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
data:
  settings.js: |
    {{- $.Values.devstudioSettings | nindent 4 }}
