---
apiVersion: v1
kind: Service
metadata:
  name: devstudio
  namespace: {{ .Release.Namespace }}
  labels:
    app: devstudio
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  type: {{ if .Values.nodePort.enabled }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - name: http-devstudio
      port: 1880
      targetPort: 1880
      protocol: TCP
      {{- if .Values.nodePort.enabled }}
      nodePort: 31880
      {{- end }}
  selector:
    app: devstudio
